src/Entity/Message.php
<?php

namespace App\Entity;

use App\Repository\MessageRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MessageRepository::class)
 */
class Message
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $contenu;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;

    /**
     * @ORM\ManyToOne(targetEntity=Sujet::class, inversedBy="messages")
     * @ORM\JoinColumn(nullable=false)
     */
    private $sujet;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getSujet(): ?Sujet
    {
        return $this->sujet;
    }

    public function setSujet(?Sujet $sujet): self
    {
        $this->sujet = $sujet;

        return $this;
    }
}

src/Entity/Sujet.php
<?php

namespace App\Entity;

use App\Repository\SujetRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SujetRepository::class)
 */
class Sujet
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;

    /**
     * @ORM\OneToMany(targetEntity=Message::class, mappedBy="sujet", orphanRemoval=true)
     */
    private $messages;

    public function __construct()
    {
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    /**
     * @return Collection<int, Message>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setSujet($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getSujet() === $this) {
                $message->setSujet(null);
            }
        }

        return $this;
    }
}

src/Controller/AccueilController.php
<?php

namespace App\Controller;

use App\Entity\Sujet;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AccueilController extends AbstractController
{
    /**
     * @Route("/", name="accueil")
     */
    public function index(): Response
    {

        $doctrine = $this->getDoctrine();

        $repository = $doctrine->getRepository(Sujet::class);

        $sujets = $repository->findAll();

        return $this->render('accueil/index.html.twig', [
            'sujets' => $sujets,
        ]);
    }
}

src/Controller/MessageController.php
<?php

namespace App\Controller;

use \DateTime;
use App\Entity\Message;
use App\Entity\Sujet;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MessageController extends AbstractController
{
    /**
     * @Route("/message/add/{id}", name="messageAdd")
     */
    public function add(Request $request, int $id): Response
    {

        $doctrine = $this->getDoctrine();

        $repository = $doctrine->getRepository(Message::class);

        if ($request->request->get('message')) {
            
            $contenu = $request->request->get('message');
            $date = new DateTime();

            $entityManager = $doctrine->getManager();

            $message = new Message();

            $message->setContenu($contenu);
            $message->setDateCreation($date);
            $message->setSujet($doctrine->getRepository(Sujet::class)->find($id));

            $entityManager->persist($message);

            $entityManager->flush();
        }

        return $this->redirectToRoute('sujet', [
            'id' => $id,
        ]);
    }
}

src/Controller/SujetController.php
<?php

namespace App\Controller;

use \DateTime;
use App\Entity\Message;
use App\Entity\Sujet;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SujetController extends AbstractController
{

    /**
     * @Route("/sujet/add", name="addSujet")
     */
    public function add(Request $request): Response
    {
        
        $doctrine = $this->getDoctrine();

        $repository = $doctrine->getRepository(Sujet::class);

        if ($request->request->get('nom')) {
            
            $nom = $request->request->get('nom');
            $description = $request->request->get('description');
            $date = new DateTime();

            $entityManager = $doctrine->getManager();

            $sujet = new Sujet();

            $sujet->setNom($nom);
            $sujet->setDescription($description);
            $sujet->setDateCreation($date);

            $entityManager->persist($sujet);

            $entityManager->flush();

            return $this->redirectToRoute('accueil');
        }

        return $this->renderForm('sujet/add.html.twig');
    }

    /**
     * @Route("/sujet/{id}", name="sujet")
     */
    public function view(Request $request, int $id): Response
    {
        $doctrine = $this->getDoctrine();

        $sujet = $doctrine->getRepository(Sujet::class)->find($id);

        if (!$sujet) {
            throw $this->createNotFoundException(
                'Aucun sujet trouvé pour cet id : '.$id
            );
        }

        $repository = $doctrine->getRepository(Message::class);

        $messages = $repository->findBy([
            'sujet' => $id
        ], ['date_creation'=>'DESC']);

        return $this->render('sujet/view.html.twig', [
            'sujet' => $sujet,
            'messages' => $messages,
        ]);
    }
}

templates/accueil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}

<br><style>{% include 'accueil/css/style.css' %}</style><br>

<div class="wrapper">
    {% for sujet in sujets %}
        <a href="{{ path('sujet', {'id': sujet.id}) }}">
        <div class="sujet">
            <p class="sujet_nom">{{ sujet.nom }}</p>
            <p class="desc">{{ sujet.description }}</p>
        </div>
        </a>
    {% endfor %}

    <a href="{{ path('addSujet') }}" class="btn2">Nouveau</a>
</div>

{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Huggii{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/sujet/add.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<br><style>{% include 'sujet/css/style.css' %}</style><br>

<div class="wrapper">

    <a href="{{ path('accueil') }}" class="btn2">Retour</a>

    <h1>Créer un nouveau sujet</h1>
    <form action="{{ path('addSujet') }}" method="post">
        <input name="nom" type="text" class="input__text" placeholder="Titre du topic"><br>
        <input name="description" type="text" class="input__text" placeholder="Description du sujet"><br>
        <input type="submit" value="Confirmer">
    </form>
</div>

{% endblock %}

templates/sujet/view.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<br><style>{% include 'sujet/css/styleView.css' %}</style><br>

<div class="wrapper">

    <a href="{{ path('accueil') }}" class="btn2">Retour</a>

    <h1>{{ sujet.nom }}</h1>
    <div class="messages">
    {% for message in messages %}
        <div class="message">
            <p class="contenu">{{ message.contenu }}</p>
        </div>
        <h2>{{ message.dateCreation|date('Y-m-d H:i:s') }}</h2>
    {% endfor %}
    </div>

    <form action="{{ path('messageAdd', {'id': sujet.id}) }}" method="post" class="post">
        <input name="message" type="text" class="input__text" placeholder="Message..."><br>
        <input type="submit" value="Poster">
    </form>
</div>

{% endblock %}